services:
  wis2-grep-broker:
    volumes:
      - ./path/to/your.ca.crt:/mosquitto/config/certs/ca.crt
      - ./path/to/your.tls.crt:/mosquitto/config/certs/tls.crt
      - ./path/to/your/tls.key:/mosquitto/config/certs/tls.key

    ports:
      - 8883:1883
  wis2-grep-api:
    ports:
      - 443:8080
