broker: ${WIS2_GREP_GB}

client_id: wis2-grep-management

subscribe_topics:
    - origin/a/wis2/#
    - cache/a/wis2/#

qos: 1

verify_data: false

validate_message: false

hook: wis2_grep.hook.NotificationMessageHook
